# SPDX-FileCopyrightText: 2023 René de Hesselle <dehesselle@web.de>
#
# SPDX-License-Identifier: MIT

on:
  push:
    branches:
      - "*"
jobs:
  pip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install build
      - name: Build package
        run: python -m build
      - name: Upload sdist
        uses: actions/upload-artifact@v3
        with:
          name: sdist
          path: dist/tkdialogs-*.tar.gz
      - name: Upload wheel
        uses: actions/upload-artifact@v3
        with:
          name: wheel
          path: dist/tkdialogs-*.whl
  conda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.10"
      - name: Install dependencies
        run: conda install conda-build
      - name: Build package
        run: conda build --output-folder . .
      - name: Upload conda
        uses: actions/upload-artifact@v3
        with:
          name: conda
          path: noarch/tkdialogs-*.tar.bz2
